### ISSUE TITLE
Tutorial - styling issues: incomplete image display, small modal size

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#4558]
## Describe the bug

1. Tutorial media items are not fully displayed - the bottom of the image is cutoff and not visible.  Example - Daily Minor Planet ([link](https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354)): green circle appears in ~center of actual image, but near bottom when displayed in modal -- see screenshots of tutorial display and actual image.
<img height="250" alt="Screen Shot 2023-05-01 at 1 54 34 PM 2" src="https://user-images.githubusercontent.com/2006101/235970088-aa6cef0b-4733-4121-8570-512806460101.png"> <img height="250" alt="Screen Shot 2023-05-03 at 10 48 27 AM" src="https://user-images.githubusercontent.com/2006101/235970111-3c48c6c8-983a-4af4-a7d7-02504086dc7d.png">

Notes:
- Issue appears to occur when tutorial is shown in centered modal *or* in task area.
- Might be similar to Issue 2 in #4557 (image display issue in survey task's confused with modal)?

2. When a volunteer visits a workflow for the first time, the tutorial appears in a pop-up modal centered in the browser window (as opposed to appearing in task area). The size of this modal is small relative to the size of the browser window -- please increase vertical size to reduce scrolling (e.g., make modal ~80% height of window) and possibly increase horizontal size. (attn: @seanmiller26)
<img width="1258" alt="Screen Shot 2023-05-01 at 1 54 34 PM" src="https://user-images.githubusercontent.com/2006101/235971656-20ebd0f1-5d61-4da7-be43-553cc3c5fa6d.png">

attn: @goplayoutside3

**Comment by eatyourgreens** [comment]
On my phone, I can’t get past the tutorial. The window can’t be scrolled here. 

![Daily Minor Planet tutorial on an iPhone XS. The bottom of the tutorial is cut off, and can’t be scrolled to bring the navigation buttons into the viewport.](https://user-images.githubusercontent.com/59547/236048259-f6bd64d0-471e-4dc6-9abd-522f83e1fb79.jpeg)

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/thumbnailer/pull/25 made height or width optional for our thumbnail service. You only need to specify one now, not both. I've opened #4561 to apply that change to thumbnail images. It won't change the displayed aspect ratio (that's fixed in the tutorial) but displayed images should be centred in their containers.

Side issue: GIFs are an accessibility problem, as playback can't be controlled by the end user. Short video clips are supported by our tutorials and would be preferable here.

**Comment by eatyourgreens** [comment]
Tutorial images should be centred now that #4561 has merged. You can try it out on [Daily Minor Planet staging](https://frontend.preview.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354).

**Comment by lcjohnso** [comment]
No, Problem 1 is not resolved.  The image does appear to be vertically centered now after #4561, but the full image is still not displayed -- and it should be.

@seanmiller26 -- Do you have an opinion regarding resizing of the pop-up modal version of the tutorial (Problem 2)?

**Comment by eatyourgreens** [comment]
>I'm wondering if, while we're touching up the tutorial, we can eliminate this 'Tutorial' subheading in grey: 
>
><img width="231" alt="Screen Shot 2023-05-10 at 10 56 53 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/095960c2-a235-4053-9d39-de90817b44c3">

That 'Tutorial' heading would be straightforward to remove. It's hard-coded into the first slide here:
https://github.com/zooniverse/front-end-monorepo/blob/948497b240d44b1c83b37e36994e47a3af9e4414/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js#L83-L86

**Comment by eatyourgreens** [comment]
That tutorial also has a `h2` heading nested inside a `h3` heading. It should really be the other way around, to make sense to a blind volunteer.
<img width="340" alt="Screenshot of the HTML for the Daily Minor Planet tutorial, which opens with a h3 heading followed by a h2." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/42a765d3-ee97-445c-80a0-8f7af5f25a8c">

**Comment by seanmiller26** [comment]
Right now the default width for the modal in my browser is 390px, and the task area is set to 400px. We could unify those sizes and make the modal 400px, but thats not a significant increase. 

I would not be opposed to making the modal more of a horizontal aspect to help with large images, blocks of text and scrolling. But I'd need to know more about some of the technical limitations.

For reference, the guidelines for characters per line in a paragraph is no more than ~75. Right now we are using ~50 per line at this width. So we do have some room to expand the width and keep the legibility intact.

**Comment by seanmiller26** [comment]
How is the height calculated at the moment? My modal window for FEM projects shows 563.04px. Where do we get that number?

**Comment by eatyourgreens** [comment]
Good question. On my phone, it fills the screen, so I've been assuming the height is set to `100%` on phones. I'd guess the desktop version is sized to the viewport height, so `60vh` or something like that. When I open browser dev tools, the tutorial shrinks to fit the restricted height of the viewport.

**Comment by eatyourgreens** [comment]
I see a width here, but not a height. That must be set as a default behaviour in the `Modal` component itself.
https://github.com/zooniverse/front-end-monorepo/blob/948497b240d44b1c83b37e36994e47a3af9e4414/packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js#L45-L63

**Comment by eatyourgreens** [comment]
Aha! The tutorial height is set here, for both the popup tutorial and the tutorial tab in the task area. `53vh` seems like a very specific length. I wonder how that was arrived at (and what breaks if we change it?)

https://github.com/zooniverse/front-end-monorepo/blob/ebd99cca2297d751ee4b1c2011251af5d8ccae05/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js#L53-L69

**Comment by goplayoutside3** [comment]
@lcjohnso @eatyourgreens  Re:
> the full image is still not displayed -- and it should be.
and
> The design of the tutorial fixes the aspect ratio of those images; a fixed height of 200px and then variable width to fit the container. Tutorial images can't be square, as a result.

Jim's right that the fixed 200px height and specific aspect ratio was a design decision made when FEM launched. Cliff would you like to change the tutorial image design to fit the entire 'header' image? It is a change we can make. This will change how some live project's tutorial images display.

**Comment by eatyourgreens** [comment]
Here's the tutorial with the height set to `73vh` and the first heading removed.

<img width="1279" alt="Screenshot of the Daily Minor Planet tutorial with the first heading removed and a much taller popup box, so that more of the tutorial text is visible upon entering the project for the first time." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/3df40c45-4b80-4beb-933a-1f74a42c8875">

**Comment by eatyourgreens** [comment]
Here's both taller (73vh) and wider (400px.) I think I prefer this version.

<img width="1278" alt="The Daily Minor Planet tutorial again, but the width is increased from 330px to 400px." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/36328667-2040-4141-bc51-eecc1c02bae0">

**Comment by eatyourgreens** [comment]
Wide box, image fit changed from `cover` to `contain`. I'm putting all these changes into #4608 too.

<img width="1278" alt="The Daily Minor Planet poup tutorial with a wider, taller box, but now the header image is constrained to be square, with largeer white margins to its left and right." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/062eadc4-8e29-4207-9d7e-4bd15e8af9ee">

**Comment by lcjohnso** [comment]
I like the height and width changes of the pop-up modal, removal of the "Tutorial" label is good, and I prefer the `contain` display of the tutorial page media items. Therefore, I'm in favor of #4608 moving ahead as currently implemented.

**Comment by eatyourgreens** [comment]
Is this fixed now that #4608 is live on the web site?

**Comment by lcjohnso** [comment]
Yes, resolved -- thanks @eatyourgreens!
